apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-prod
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: backend
        image: 192.168.1.184:9443/3tier/backend:prod-latest
        env:
        - name: APP_ENV
          value: prod
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-prod-service:5432/app_prod
        - name: SPRING_DATASOURCE_USERNAME
          value: prod_admin
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-prod-secret
              key: password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-prod-service
  namespace: prod
spec:
  ports:
  - port: 8080
  selector:
    app: backend-prod
