apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tier-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.1.184/git/3tier-app.git'
    targetRevision: HEAD
    path: deployments/prod/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
